project:
  type: website
  output-dir: docs
website:
  title: "Soleil Michaud"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - about.qmd
      - courses.qmd
      - research.qmd
      - teaching.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



